---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javacalculator-app
      version: latest
  template:
    metadata:
      name: javacalculator-pod
      labels:
        app: javacalculator-app
        version: latest
    spec:
      containers:
      - name: javacalculator-container
        image: deepikasamudrala/calculator_java:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: javacalculator-svc
  labels:
    app: javacalculator-app
spec:
  selector:
    app: javacalculator-app
    version: latest
  type: NodePort
  ports:
  - nodePort: 31113
    port: 8080
    targetPort: 8080
