apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacalci-deployment
  labels:
	app: javacalculator
spec:
  replicas: 2
  selector:
    matchlabels:
      app: javacalculator
template:
  metadata:
    labels:
      app: javacalculator
  spec:
    containers:
    - name: javacalciapp
	  image: calculator_java:latest
	  ports:
 	  - containerPort:8080
---
apiVersion: v1
kind: Service
metadata:
  name: javacalculator
  namespace: devops-tools
spec:
  type: LoadBalancer
  selector:
    app: javacalculator
  ports:
  - name: apachetomcat
    port: 8080
    targetPort: 8080
    protocol: TCP
    
