apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
	app: tomcat
spec:
  replicas: 2
  selector:
    matchlabels:
      app: tomcat
template:
  metadata:
    labels:
      app: tomcat
  spec:
    containers:
    - name: tomcat
	  image: calculator_java:latest
	  ports:
 	  - containerPort:8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: devops-tools
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
  - name: tomcat
    port: 8080
    targetPort: 8080
    protocol: TCP
    
