---
apiVersion: v1
kind: Service
metadata:
  name: javacalculator
  namespace: ja-ca
spec:
  type: LoadBalancer
  selector:
    app: javacalculator
  ports:
  - name: apachetomcat
    port: 8080
    targetPort: 8080
    protocol: TCP
...